name: Scheduled Render Redeploy

on:
  schedule:
    # Codziennie o 21:20 czasu polskiego (czyli 19:20 UTC)
    - cron: '20 19 * * *'

jobs:
  scheduled-redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Redeploy on Render
        run: curl -X POST "$RENDER_DEPLOY_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}